"""Generated by scripts/gen_root_pytest.py — do not hand-edit.

This component's tests import from a package called ``app``, and so does every
other component's. Running ``pytest`` at the repo root puts them all in one
interpreter, so before pytest imports anything under this directory, claim the
name for this backend.

Running ``pytest`` from inside this directory still works exactly as before:
the repo root goes on the path, the claim is a no-op, and nothing else changes.
"""

from __future__ import annotations

import pathlib
import sys

_REPO = pathlib.Path(__file__).resolve().parent.parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from twinkit.testing import claim_backend  # noqa: E402  (path set up above)

claim_backend(__file__)
