#!/usr/bin/env python3
"""Write one page per module under Learn/modules/.

Each page is a thin shell: a title, a mount point naming its module, and the
three scripts. learn.js renders the module from course.js, so the questions
and links live in one place and the pages cannot drift from it. The shells
are generated so a new module in course.js gets its page by running this.

    python3 Learn/scripts/gen_pages.py           # write the pages
    python3 Learn/scripts/gen_pages.py --check   # fail if any is missing/stale
"""

from __future__ import annotations

import html
import json
import pathlib
import sys

LEARN = pathlib.Path(__file__).resolve().parent.parent
PREFIX = "window.COURSE = "

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title} · Learn the twins</title>
<link rel="stylesheet" href="../../CustomerSetup/shared/setup.css" />
<link rel="stylesheet" href="../learn.css" />
</head>
<!-- Generated by Learn/scripts/gen_pages.py from course.js. Do not hand-edit. -->
<body class="learn">
<main id="learn" data-page="module" data-module="{mid}">
  <noscript>This page is drawn from Learn/course.js and needs JavaScript.</noscript>
</main>
<script src="../course.js"></script>
<script src="../learn.js"></script>
<script src="../../CustomerSetup/shared/setup.js"></script>
</body>
</html>
"""


def load_course() -> dict:
    text = (LEARN / "course.js").read_text()
    body = text[text.index(PREFIX) + len(PREFIX):].rstrip()
    return json.loads(body[:-1])


def filename(mid: str) -> str:
    return mid.lower() + ".html"


def page(module: dict) -> str:
    return TEMPLATE.format(title=html.escape(module["title"]), mid=html.escape(module["id"]))


def main() -> int:
    check = "--check" in sys.argv
    out = LEARN / "modules"
    out.mkdir(exist_ok=True)
    stale = []
    for m in load_course()["modules"]:
        target = out / filename(m["id"])
        want = page(m)
        if target.exists() and target.read_text() == want:
            continue
        if check:
            stale.append(target.name)
        else:
            target.write_text(want)
    if stale:
        print("stale or missing module pages: " + ", ".join(stale))
        return 1
    print("module pages are current" if check else "module pages written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
