"""Data models for the IR7000 + PowerCool digital twin.

Same conventions as the other twins in this repo: snake_case in Python,
camelCase over the wire (activeRegions, itLoadWatts, liquidWatts, flowLpm,
regionIds, ...), so the React frontend can consume responses directly. None
of the fields here camelize ambiguously (no embedded numbers/acronyms), so
no explicit aliases are needed — if you add one that does, pin it with
``Field(alias=...)`` and check frontend/src/types.ts by hand (see CLAUDE.md).

The twist versus every earlier twin: the subject is a **thermal system**,
not a computer. The Dell Integrated Rack 7000 (IR7000) is Dell's Open
Compute ORv3-based rack for extreme-density AI, and PowerCool is the liquid
cooling that makes it survivable — an in-rack coolant distribution unit
(CDU), vertical manifolds, cold plates on the IT payload, and an enclosed
rear-door heat exchanger for the heat that still leaves by air. So the
"anatomy" is the rack *as a cooling loop*, and the "power-on" trace is the
loop's commissioning and thermal ramp: fill, pump, verify, then let the IT
load arrive — with an energy-conservation invariant (liquid + air heat
removal must exactly equal the IT load) standing where the compute twins
put their phase machines.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

RegionKind = Literal[
    "cdu",        # the in-rack coolant distribution unit — pumps + heat exchanger
    "manifold",   # vertical supply and return manifolds
    "coldplate",  # IT bays whose chips sit under cold plates (the heat source)
    "airdoor",    # enclosed rear-door heat exchanger (eRDHx) — the air-side catch
    "power",      # power shelves / busbar feeding the IT load
    "facility",   # facility water connection — where the heat finally goes
    "sensor",     # leak, flow, and temperature instrumentation
]

# Thermal bring-up phases, in order. The loop is proven before the load
# exists: fill and degas, start pumps, verify every branch, bring the air
# door online — only then may IT load (heat) arrive and ramp to steady state.
ThermalPhase = Literal[
    "off",       # rack integrated, loop dry, everything dark
    "fill",      # loop filled with treated coolant and vacuum-degassed
    "pump",      # CDU pumps start; manifolds pressurize
    "verify",    # leak check + per-branch flow verification (commissioning)
    "airdoor",   # rear-door heat exchanger fans and coil come online
    "load",      # IT payload powers on — heat appears on the cold plates
    "balance",   # pumps and fans modulate; temperatures settle
    "steady",    # full design load, steady state, heat balance holds
]


class CamelModel(BaseModel):
    """Base model: snake_case in Python, camelCase over the wire."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class Photo(CamelModel):
    """An image of the part; ``credit`` must always be rendered by the UI."""

    url: str
    caption: str
    credit: str


class RackRegion(CamelModel):
    id: str
    kind: RegionKind
    label: str
    x: float
    y: float
    w: float
    h: float
    description: str
    photo: Photo | None = None


class SourceLink(CamelModel):
    label: str
    url: str


class Stat(CamelModel):
    label: str
    value: str


class RackAnatomy(CamelModel):
    """The rack-as-loop floorplan, annotated. ``width``/``height`` set the viewBox."""

    id: str
    name: str
    vendor: str
    form_factor: str
    generation: str
    year: int
    width: float
    height: float
    regions: list[RackRegion]
    stats: list[Stat]
    sources: list[SourceLink] = Field(default_factory=list)
    overview: str
    photo: Photo | None = None


class ThermalState(CamelModel):
    """One step of the thermal bring-up; pure data the renderer consumes.

    The defining relation — enforced in tests/test_engine.py — is energy
    conservation: ``liquid_watts + air_watts == it_load_watts`` on every
    step. Heat is not managed; it is conserved, and the loop's only job is
    to move all of it somewhere else.
    """

    step: int
    phase: ThermalPhase
    label: str
    description: str
    # Region ids in the rack anatomy lit up at this step.
    active_regions: list[str]
    # Heat generated by the IT payload this step (0 until the load phase).
    it_load_watts: int
    # Heat leaving through the liquid loop (cold plates → CDU → facility).
    liquid_watts: int
    # Heat leaving through air, captured by the rear-door heat exchanger.
    air_watts: int
    # Coolant flow through the manifolds, liters per minute.
    flow_lpm: int
    # Illustrative wall-clock seconds since commissioning began.
    elapsed_seconds: int
    # UI dwell ticks; long stages (the leak/flow verification) get more.
    cycle_cost: int = 1


class ThermalResponse(CamelModel):
    trace: list[ThermalState]


class CatalogOption(CamelModel):
    id: str
    name: str
    summary: str  # one sentence
    # A paragraph for a technically skilled reader new to liquid cooling;
    # spell out jargon (CDU, ORv3, eRDHx, quick disconnect, PG25, ...) on
    # first use.
    details: str


class CatalogCategory(CamelModel):
    id: str
    name: str
    blurb: str
    limits: str  # e.g. "33–264 kW per rack today, roadmap to 480 kW"
    # Rack regions this category slots into (ids from anatomy.py).
    region_ids: list[str] = Field(default_factory=list)
    options: list[CatalogOption]


class UseCaseItem(CamelModel):
    category_id: str
    option_id: str
    qty: int
    rationale: str


class UseCase(CamelModel):
    id: str
    title: str
    summary: str
    narrative: list[str]  # paragraphs
    config: list[UseCaseItem]
    outcomes: list[Stat] = Field(default_factory=list)
