#!/usr/bin/env python3
"""Render the component table into CLAUDE.md and README.md from components.json.

Both files listed the components in prose, and both had drifted: the README
still describes the GPU app as if it were the whole repo, and CLAUDE.md's
opening paragraph names twenty-five directories in a sentence.

The table between the COMPONENT-TABLE markers is generated. Everything outside
them is hand-written and left alone.

    python3 scripts/gen_docs.py           # rewrite the tables
    python3 scripts/gen_docs.py --check    # fail if they are stale (CI)
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN COMPONENT-TABLE (generated by scripts/gen_docs.py) -->"
END = "<!-- END COMPONENT-TABLE -->"

TARGETS = ["CLAUDE.md", "README.md"]


def table() -> str:
    data = json.loads((ROOT / "components.json").read_text())
    order = {status: i for i, status in enumerate(data["statuses"])}
    rows = sorted(
        data["components"], key=lambda c: (order[c["status"]], c["family"], c["name"])
    )
    lines = [
        BEGIN,
        "",
        f"{len(rows)} components. Generated from `components.json`; start any of them with",
        "`scripts/dev.sh <name>` and list them with `scripts/dev.sh --list`. Statuses are",
        "documented in [`docs/LIFECYCLE.md`](docs/LIFECYCLE.md).",
        "",
        "| Component | Status | Family | Backend | Frontend | Trace | What it is |",
        "|---|---|---|---|---|---|---|",
    ]
    for component in rows:
        lines.append(
            "| `{name}` | {status} | {family} | {backend} | {frontend} | {trace} | {description} |".format(
                name=component["name"],
                status=component["status"],
                family=component["family"],
                backend=component["backendPort"] or "—",
                frontend=component["frontendPort"] or "—",
                trace=f"`{component['traceEndpoint']}`" if component["traceEndpoint"] else "—",
                description=component["description"].replace("|", "\\|"),
            )
        )
    lines += ["", END]
    return "\n".join(lines)


def render(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END) :]
        return head + block + tail
    # First insertion: after the document's title line.
    lines = text.splitlines(True)
    at = 1 if lines and lines[0].startswith("# ") else 0
    return "".join(lines[:at]) + "\n" + block + "\n" + "".join(lines[at:])


def main() -> int:
    block = table()
    stale = []
    for name in TARGETS:
        path = ROOT / name
        current = path.read_text()
        updated = render(current, block)
        if current == updated:
            continue
        if "--check" in sys.argv:
            stale.append(name)
        else:
            path.write_text(updated)
            print(f"updated {name}")
    if stale:
        print("stale component table in: " + ", ".join(stale))
        print("run python3 scripts/gen_docs.py")
        return 1
    if "--check" in sys.argv:
        print("component tables are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
