#!/usr/bin/env python3
"""Write the per-backend conftest.py that makes the root suite possible.

Generated rather than hand-copied for the reason twinkit exists: a file that
has to be identical in 42 places will not stay identical.

    python3 scripts/gen_root_pytest.py           # write them
    python3 scripts/gen_root_pytest.py --check    # fail if any is missing/stale
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

TEMPLATE = '''"""Generated by scripts/gen_root_pytest.py — do not hand-edit.

This component's tests import from a package called ``app``, and so does every
other component's. Running ``pytest`` at the repo root puts them all in one
interpreter, so before pytest imports anything under this directory, claim the
name for this backend.

Running ``pytest`` from inside this directory still works exactly as before:
the repo root goes on the path, the claim is a no-op, and nothing else changes.
"""

from __future__ import annotations

import pathlib
import sys

_REPO = pathlib.Path(__file__).resolve().parent.parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from twinkit.testing import claim_backend  # noqa: E402  (path set up above)

claim_backend(__file__)
'''


def missing_ci_shards() -> list[str]:
    """Components whose tests the sharded CI job would silently skip."""
    ci = ROOT / ".gitlab-ci.yml"
    if not ci.exists():
        return []
    shards = {
        line.strip()[2:].strip()
        for line in ci.read_text().splitlines()
        if line.strip().startswith("- ") and " " not in line.strip()[2:].strip()
    }
    return [
        backend.parent.name
        for backend in sorted(ROOT.glob("*/backend"))
        if (backend / "tests").is_dir() and backend.parent.name not in shards
    ]


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    written = 0
    for backend in sorted(ROOT.glob("*/backend")):
        if not (backend / "tests").is_dir():
            continue
        target = backend / "conftest.py"
        if target.exists() and target.read_text() == TEMPLATE:
            continue
        if check:
            stale.append(str(target.relative_to(ROOT)))
        else:
            target.write_text(TEMPLATE)
            written += 1
    if stale:
        print("missing or stale conftest.py:\n  " + "\n  ".join(stale))
        print("run python3 scripts/gen_root_pytest.py")
        return 1
    unsharded = missing_ci_shards()
    if unsharded:
        print("components with tests but no CI shard in .gitlab-ci.yml: " + ", ".join(unsharded))
        return 1
    print("conftests are current" if check else f"wrote {written} conftest.py files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
